build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank loans related PROD APIs "
  environment: "prod"
  contactDetails:
    name: "Amaal Grega - Manager"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934