build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank loans related QA APIs "
  environment: "QA"
  contactDetails:
    name: "Amaal Grega - Tester"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934