server:
  port: 8080
spring:
  application:
    name: "accounts"
  config:
    import: "optional:configserver:http://localhost:8071/"



  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
profiles:
  active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    com:
      ms:
        accounts: DEBUG